"""Generate src/data/cie1931-cmf.ts from the CIE 1931 2-degree standard observer.

Provenance: CIE 015:2018 "Colorimetry", 4th ed., Table T.4 (CIE 1931 standard
colorimetric observer), as distributed by colour-science
(colour.MSDS_CMFS['CIE 1931 2 Degree Standard Observer']). Tabulated here at 5 nm, the
CIE's own standard interval, from 360 to 830 nm.

Also emits reference blackbody chromaticities computed by colour-science at 1 nm with
its own integration, which the TypeScript test suite uses as an independent check.

Run:  python3 scripts/generate_cie_cmf.py
"""
import pathlib

import colour

OUT = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'data' / 'cie1931-cmf.ts'

cmfs = colour.MSDS_CMFS['CIE 1931 2 Degree Standard Observer']
rows = []
for wavelength in range(360, 831, 5):
    x, y, z = cmfs[wavelength]
    rows.append(f'  [{wavelength}, {x:.8e}, {y:.8e}, {z:.8e}],')

references = []
for T in [1500, 2000, 3000, 4000, 5000, 6500, 10000, 20000, 50000, 100000]:
    sd = colour.sd_blackbody(T, colour.SpectralShape(360, 830, 1))
    xy = colour.XYZ_to_xy(colour.sd_to_XYZ(sd, cmfs, method='Integration'))
    references.append(f'  [{T}, {xy[0]:.8f}, {xy[1]:.8f}],')

source = f'''/**
 * CIE 1931 2-degree standard colorimetric observer: colour-matching functions.
 *
 * Data layer (CLAUDE.md §20). Provenance: CIE 015:2018 "Colorimetry", 4th edition, Table
 * T.4, as distributed by colour-science {colour.__version__}. Tabulated at 5 nm — the CIE's
 * standard interval — from 360 to 830 nm.
 *
 * GENERATED by scripts/generate_cie_cmf.py. Do not edit by hand; regenerate instead.
 */

/** Rows of [wavelength (nm), x-bar, y-bar, z-bar]. */
export const CIE1931_CMF_5NM: readonly (readonly [number, number, number, number])[] = [
{chr(10).join(rows)}
];

/**
 * Blackbody chromaticities (x, y) computed independently by colour-science at 1 nm
 * resolution, for testing. Rows of [temperature (K), x, y].
 */
export const BLACKBODY_CHROMATICITY_REFERENCE: readonly (readonly [number, number, number])[] = [
{chr(10).join(references)}
];
'''
OUT.write_text(source)
print(f'wrote {OUT} ({len(rows)} wavelengths, {len(references)} references)')
